import { CheckCircle, FileText, FunnelSimple, MagnifyingGlass, Plus } from "@phosphor-icons/react"
import { useMemo, useState } from "react"
import { Link } from "react-router-dom"
import { PageHeader } from "../components/WorkspaceComponents"
import { formatDate } from "../lib/format"
import { useWorkspace } from "../state/WorkspaceContext"

export function ReportsPage() {
  const { company } = useWorkspace()
  const [query, setQuery] = useState("")
  const [customerId, setCustomerId] = useState("all")
  const capturedIds = useMemo(() => new Set(company.capturedReports.map((report) => report.id)), [company.capturedReports])
  const allReports = useMemo(() => [...company.reports, ...company.capturedReports], [company.reports, company.capturedReports])
  const reports = useMemo(() => allReports.filter((report) => {
    const customer = company.customers.find((c) => c.id === report.customerId)
    const system = customer?.systems.find((s) => s.id === report.systemId)
    return (customerId === "all" || report.customerId === customerId) && `${report.id} ${report.fileName} ${customer?.name} ${system?.name}`.toLowerCase().includes(query.toLowerCase())
  }).sort((a,b) => b.serviceDate.localeCompare(a.serviceDate)), [allReports, company.customers, customerId, query])
  return <div className="mx-auto max-w-[1480px] px-4 py-7 sm:px-6 lg:px-8 lg:py-9"><PageHeader eyebrow="Evidence library" title="Source Reports" description="Service reports and structured records available for review." actions={<Link to="/reports/new" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-blue-600 bg-blue-600 px-4 text-sm font-semibold text-white shadow-[0_8px_22px_rgba(37,99,235,0.2)] transition hover:border-blue-700 hover:bg-blue-700 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-blue-500/25"><Plus size={17} weight="bold" aria-hidden="true" />Add report</Link>} />
    <div className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search reports</span><MagnifyingGlass size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search report ID, file, customer, or system" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-500/15" /></label><label className="relative"><span className="sr-only">Filter by customer</span><FunnelSimple size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" /><select value={customerId} onChange={(e) => setCustomerId(e.target.value)} className="h-11 min-w-56 rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm font-semibold outline-none focus:border-blue-500"><option value="all">All customers</option>{company.customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label></div>
    <div className="mt-5 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-card"><div className="hidden grid-cols-[1fr_1.35fr_1fr_0.75fr_0.7fr] gap-4 border-b bg-slate-50 px-5 py-3 text-[10px] font-bold uppercase tracking-[0.1em] text-slate-500 md:grid"><span>Report</span><span>Customer & system</span><span>Service date</span><span>Pages</span><span>Status</span></div><div className="divide-y divide-slate-100">{reports.map((report) => { const customer = company.customers.find((c) => c.id === report.customerId); const system = customer?.systems.find((s) => s.id === report.systemId); const captured = capturedIds.has(report.id); return <Link key={report.id} to={`/reports/${report.id}`} className="grid gap-3 px-4 py-4 hover:bg-blue-50/30 md:grid-cols-[1fr_1.35fr_1fr_0.75fr_0.7fr] md:items-center md:px-5"><span className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700"><FileText size={18} aria-hidden="true" /></span><span className="min-w-0"><span className="numeric block text-sm font-bold text-slate-950">{report.id}</span><span className="block truncate text-[10px] text-slate-500">{report.fileName}</span></span></span><span><span className="block text-sm font-semibold text-slate-900">{customer?.name}</span><span className="block text-xs text-slate-500">{system?.name}</span></span><span className="text-sm font-semibold text-slate-700">{formatDate(report.serviceDate)}</span><span className="numeric text-sm text-slate-600">{report.pageCount} pages</span><span className={`inline-flex w-fit items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${captured ? "bg-blue-50 text-blue-800" : "bg-teal-50 text-teal-800"}`}><CheckCircle size={14} weight="fill" aria-hidden="true" />{captured ? "Ready" : "Analyzed"}</span></Link>})}{!reports.length ? <div className="px-5 py-12 text-center"><p className="text-sm font-bold text-slate-900">No reports match these filters.</p><p className="mt-1 text-xs text-slate-500">Try another search or customer.</p></div> : null}</div></div>
    <p className="mt-3 text-xs font-medium text-slate-500">Showing {reports.length} of {allReports.length} reports</p>
  </div>
}
