import { ArrowLeft, CheckCircle, FilePdf, LinkSimple, NotePencil, Wrench } from "@phosphor-icons/react"
import { Link, useParams } from "react-router-dom"
import { FindingStatusBadge, MeasurementStatus } from "../components/StatusBadges"
import { PageHeader, PriorityBadge } from "../components/WorkspaceComponents"
import { findVisit } from "../data/workspace"
import { formatDate, formatMeasurement, formatRange } from "../lib/format"
import { isOutOfRange } from "../lib/findings"
import { useDecisions } from "../state/DecisionContext"
import { useWorkspace } from "../state/WorkspaceContext"
import type { CapturedReportMeasurement, CapturedSourceReport, Company } from "../types"
import { NotFound } from "./CustomerDetailsPage"

export function ReportDetailsPage() {
  const { reportId } = useParams()
  const { company } = useWorkspace()
  const { findings } = useDecisions()
  const capturedReport = company.capturedReports.find((item) => item.id === reportId)
  if (capturedReport) return <CapturedReportDetails company={company} report={capturedReport} />
  const report = company.reports.find((item) => item.id === reportId)
  const context = report ? findVisit(company, report.visitId) : undefined
  if (!report || !context) return <NotFound label="source report" to="/reports" />
  const { customer, system, visit } = context
  const technician = company.users.find((user) => user.id === report.technicianId)
  const linkedFindings = findings.filter((finding) => finding.affectedVisitIds.includes(visit.id))
  return <div className="mx-auto max-w-[1480px] px-4 py-7 sm:px-6 lg:px-8 lg:py-9">
    <Link to="/reports" className="mb-5 inline-flex min-h-11 items-center gap-2 rounded-xl px-2 text-sm font-semibold text-slate-600 hover:bg-white hover:text-slate-950"><ArrowLeft size={17} weight="bold" />Source Reports</Link>
    <PageHeader eyebrow="Analyzed source report" title={report.id} description={`${customer.name} · ${system.name} · Service date ${formatDate(report.serviceDate)}`} />
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(520px,1.08fr)_minmax(420px,0.92fr)]">
      <section aria-labelledby="preview-title"><div className="mb-3 flex items-center justify-between"><h2 id="preview-title" className="text-sm font-bold text-slate-950">Report preview</h2><span className="text-xs font-semibold text-slate-500">{report.pageCount} pages · Read only</span></div><div className="rounded-3xl bg-slate-900 p-3 shadow-[0_24px_60px_rgba(15,23,42,0.18)] sm:p-6"><div className="mx-auto aspect-[8.5/11] max-w-[680px] overflow-hidden rounded-sm bg-white p-[6%] text-slate-800 shadow-2xl"><div className="flex items-start justify-between border-b-2 border-blue-700 pb-5"><div><div className="flex items-center gap-2 text-blue-800"><span className="grid size-8 place-items-center rounded-lg bg-blue-700 text-white"><Wrench size={17} weight="bold" /></span><span className="text-[clamp(9px,1.2vw,14px)] font-bold">CLEARFLOW WATER SERVICES</span></div><h3 className="mt-4 text-[clamp(18px,3vw,34px)] font-bold tracking-tight text-slate-950">Water Treatment Service Report</h3></div><FilePdf size={38} className="text-blue-700" weight="duotone" /></div><div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-3 text-[clamp(8px,1vw,12px)]"><PreviewField label="Report ID" value={report.id} /><PreviewField label="Service date" value={formatDate(report.serviceDate)} /><PreviewField label="Customer" value={customer.name} /><PreviewField label="System" value={system.name} /><PreviewField label="Technician" value={technician?.name ?? "Unknown"} /><PreviewField label="Location" value={customer.location} /></div><table className="mt-7 w-full border-collapse text-left text-[clamp(7px,0.95vw,11px)]"><thead><tr className="bg-slate-100"><th className="p-2">Parameter</th><th className="p-2">Result</th><th className="p-2">Configured range</th><th className="p-2">Status</th></tr></thead><tbody>{visit.measurements.map((m) => <tr key={m.id} className="border-b"><td className="p-2 font-semibold">{m.parameterName}</td><td className="p-2">{formatMeasurement(m)}</td><td className="p-2">{formatRange(m)}</td><td className="p-2">{isOutOfRange(m) ? "Review" : "In range"}</td></tr>)}</tbody></table><div className="mt-7 border-t pt-4"><p className="text-[clamp(8px,1vw,12px)] font-bold uppercase tracking-wider text-slate-500">Service observations</p><p className="mt-2 text-[clamp(8px,1vw,12px)] leading-relaxed text-slate-700">Routine service completed. Measurements, configured ranges, observations, and recorded actions are documented in the visit record.</p></div><div className="mt-9 flex justify-between border-t pt-4 text-[clamp(7px,0.9vw,10px)] text-slate-500"><span>{report.fileName}</span><span>Page 1 of {report.pageCount}</span></div></div></div></section>
      <div className="space-y-5"><section className="card-surface rounded-3xl p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-blue-700">WaterOps Intelligence</p><h2 className="mt-1 text-lg font-bold text-slate-950">Extracted record</h2></div><span className="inline-flex items-center gap-1.5 rounded-full bg-teal-50 px-2.5 py-1 text-xs font-semibold text-teal-800"><CheckCircle size={14} weight="fill" />Analysis complete</span></div><dl className="mt-5 grid grid-cols-2 gap-4 rounded-2xl bg-slate-50 p-4 text-xs"><div><dt className="text-slate-500">Received</dt><dd className="mt-1 font-semibold text-slate-900">{formatDate(report.receivedAt.slice(0,10))}</dd></div><div><dt className="text-slate-500">Completed</dt><dd className="mt-1 font-semibold text-slate-900">2 minutes after receipt</dd></div><div><dt className="text-slate-500">Technician</dt><dd className="mt-1 font-semibold text-slate-900">{technician?.name}</dd></div><div><dt className="text-slate-500">Linked visit</dt><dd className="mt-1"><Link to={`/customers/${customer.id}/systems/${system.id}`} className="font-semibold text-blue-700">{formatDate(visit.date)}</Link></dd></div></dl></section>
        <section className="card-surface rounded-3xl p-5"><h2 className="text-lg font-bold text-slate-950">Measurements & notes</h2><div className="mt-4 space-y-3">{visit.measurements.map((m) => <div key={m.id} className="rounded-2xl border border-slate-100 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold text-slate-950">{m.parameterName}</p><p className="numeric mt-0.5 text-xs text-slate-500">{formatRange(m)}</p></div><div className="text-right"><p className="numeric text-sm font-bold text-slate-950">{formatMeasurement(m)}</p><div className="mt-1"><MeasurementStatus outOfRange={isOutOfRange(m)} /></div></div></div><p className="mt-3 flex gap-2 text-xs leading-5 text-slate-600"><NotePencil size={15} className="mt-0.5 shrink-0" />{m.technicianNote}</p>{m.action ? <p className="mt-2 rounded-xl bg-blue-50 px-3 py-2 text-xs text-blue-900"><strong>Recorded action:</strong> {m.action.description}</p> : null}</div>)}</div></section>
        <section className="card-surface rounded-3xl p-5"><div className="flex items-center gap-2"><LinkSimple size={18} className="text-blue-700" /><h2 className="font-bold text-slate-950">Linked findings</h2></div>{linkedFindings.length ? <div className="mt-4 space-y-3">{linkedFindings.map((finding) => <Link key={finding.id} to={`/findings/${finding.id}`} className="block rounded-2xl border border-slate-100 p-3 hover:border-blue-200"><div className="flex flex-wrap gap-2"><PriorityBadge priority={finding.priority} /><FindingStatusBadge status={finding.status} /></div><p className="mt-2 text-sm font-bold text-slate-950">{finding.findingType}</p></Link>)}</div> : <p className="mt-3 text-xs leading-5 text-slate-600">No findings cite this service report as evidence.</p>}</section>
      </div>
    </div>
  </div>
}

function PreviewField({ label, value }: { label: string; value: string }) { return <div><p className="font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-800">{value}</p></div> }

function CapturedReportDetails({ company, report }: { company: Company; report: CapturedSourceReport }) {
  const customer = company.customers.find((item) => item.id === report.customerId)
  const system = customer?.systems.find((item) => item.id === report.systemId)
  const technician = company.users.find((item) => item.id === report.technicianId)
  if (!customer || !system || !technician) return <NotFound label="source report" to="/reports" />

  return <div className="mx-auto max-w-[1480px] px-4 py-7 sm:px-6 lg:px-8 lg:py-9">
    <Link to="/reports" className="mb-5 inline-flex min-h-11 items-center gap-2 rounded-xl px-2 text-sm font-semibold text-slate-600 hover:bg-white hover:text-slate-950"><ArrowLeft size={17} weight="bold" aria-hidden="true" />Source Reports</Link>
    <PageHeader eyebrow="Source report" title={report.id} description={`${customer.name} · ${system.name} · Service date ${formatDate(report.serviceDate)}`} />
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(520px,1.08fr)_minmax(420px,0.92fr)]">
      <section aria-labelledby="preview-title"><div className="mb-3 flex items-center justify-between"><h2 id="preview-title" className="text-sm font-bold text-slate-950">Report preview</h2><span className="text-xs font-semibold text-slate-500">{report.pageCount} pages · Read only</span></div><div className="rounded-3xl bg-slate-900 p-3 shadow-[0_24px_60px_rgba(15,23,42,0.18)] sm:p-6"><div className="mx-auto aspect-[8.5/11] max-w-[680px] overflow-hidden rounded-sm bg-white p-[6%] text-slate-800 shadow-2xl"><div className="flex items-start justify-between border-b-2 border-blue-700 pb-5"><div><div className="flex items-center gap-2 text-blue-800"><span className="grid size-8 place-items-center rounded-lg bg-blue-700 text-white"><Wrench size={17} weight="bold" /></span><span className="text-[clamp(9px,1.2vw,14px)] font-bold">CLEARFLOW WATER SERVICES</span></div><h3 className="mt-4 text-[clamp(18px,3vw,34px)] font-bold tracking-tight text-slate-950">{report.title}</h3></div><FilePdf size={38} className="text-blue-700" weight="duotone" /></div><div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-3 text-[clamp(8px,1vw,12px)]"><PreviewField label="Report ID" value={report.id} /><PreviewField label="Service date" value={formatDate(report.serviceDate)} /><PreviewField label="Customer" value={customer.name} /><PreviewField label="System" value={system.name} /><PreviewField label="Technician" value={technician.name} /><PreviewField label="Location" value={customer.location} /></div><table className="mt-7 w-full border-collapse text-left text-[clamp(7px,0.95vw,11px)]"><thead><tr className="bg-slate-100"><th className="p-2">Parameter</th><th className="p-2">Sampling point</th><th className="p-2">Result</th><th className="p-2">Configured range</th></tr></thead><tbody>{report.measurements.map((measurement) => <tr key={measurement.id} className="border-b"><td className="p-2 font-semibold">{measurement.parameterName}</td><td className="p-2">{measurement.samplePoint || "—"}</td><td className="numeric p-2">{capturedValue(measurement)}</td><td className="numeric p-2">{capturedRange(measurement)}</td></tr>)}</tbody></table><div className="mt-7 border-t pt-4"><p className="text-[clamp(8px,1vw,12px)] font-bold uppercase tracking-wider text-slate-500">Service observations</p><p className="mt-2 text-[clamp(8px,1vw,12px)] leading-relaxed text-slate-700">{report.observations || "No general observations recorded."}</p></div><div className="mt-9 flex justify-between border-t pt-4 text-[clamp(7px,0.9vw,10px)] text-slate-500"><span>{report.fileName}</span><span>Page 1 of {report.pageCount}</span></div></div></div></section>
      <div className="space-y-5"><section className="card-surface rounded-3xl p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-blue-700">WaterOps Intelligence</p><h2 className="mt-1 text-lg font-bold text-slate-950">Structured record</h2></div><span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-800"><CheckCircle size={14} weight="fill" aria-hidden="true" />Ready</span></div><dl className="mt-5 grid grid-cols-2 gap-4 rounded-2xl bg-slate-50 p-4 text-xs"><div><dt className="text-slate-500">Captured</dt><dd className="mt-1 font-semibold text-slate-900">{formatDate(report.receivedAt.slice(0, 10))}</dd></div><div><dt className="text-slate-500">Entry method</dt><dd className="mt-1 font-semibold text-slate-900">{report.captureMethod === "upload" ? "PDF upload" : "Manual entry"}</dd></div><div><dt className="text-slate-500">Technician</dt><dd className="mt-1 font-semibold text-slate-900">{technician.name}</dd></div><div><dt className="text-slate-500">Water system</dt><dd className="mt-1"><Link to={`/customers/${customer.id}/systems/${system.id}`} className="font-semibold text-blue-700">{system.name}</Link></dd></div>{report.fileSize ? <div className="col-span-2"><dt className="text-slate-500">Source file</dt><dd className="mt-1 truncate font-semibold text-slate-900">{report.fileName} · {(report.fileSize / 1024 / 1024).toFixed(2)} MB</dd></div> : null}</dl></section>
        <section className="card-surface rounded-3xl p-5"><h2 className="text-lg font-bold text-slate-950">Measurements & notes</h2><div className="mt-4 space-y-3">{report.measurements.map((measurement) => { const hasRange = measurement.minimum !== undefined && measurement.maximum !== undefined; const out = hasRange && (measurement.value < measurement.minimum! || measurement.value > measurement.maximum!); return <div key={measurement.id} className="rounded-2xl border border-slate-100 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-bold text-slate-950">{measurement.parameterName}</p><p className="mt-0.5 text-xs text-slate-500">{measurement.samplePoint || "No sampling point"} · {capturedRange(measurement)}</p></div><div className="text-right"><p className="numeric text-sm font-bold text-slate-950">{capturedValue(measurement)}</p>{hasRange ? <div className="mt-1"><MeasurementStatus outOfRange={out} /></div> : <span className="mt-1 inline-flex rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold text-slate-600">No configured range</span>}</div></div>{measurement.technicianNote ? <p className="mt-3 flex gap-2 text-xs leading-5 text-slate-600"><NotePencil size={15} className="mt-0.5 shrink-0" aria-hidden="true" />{measurement.technicianNote}</p> : null}{measurement.action ? <p className="mt-2 rounded-xl bg-blue-50 px-3 py-2 text-xs text-blue-900"><strong>Recorded action:</strong> {measurement.action}</p> : null}</div> })}</div></section>
        <section className="card-surface rounded-3xl p-5"><div className="flex items-center gap-2"><LinkSimple size={18} className="text-blue-700" aria-hidden="true" /><h2 className="font-bold text-slate-950">Report record</h2></div><p className="mt-3 text-xs leading-5 text-slate-600">This report is available in the source-report library with its confirmed measurements and notes.</p></section>
      </div>
    </div>
  </div>
}

function capturedValue(measurement: CapturedReportMeasurement) {
  return `${measurement.value}${measurement.unit ? ` ${measurement.unit}` : ""}`
}

function capturedRange(measurement: CapturedReportMeasurement) {
  if (measurement.minimum === undefined || measurement.maximum === undefined) return "No configured range"
  return `${measurement.minimum}–${measurement.maximum}${measurement.unit ? ` ${measurement.unit}` : ""}`
}
